### ISSUE TITLE
#error

### ISSUE THREAD

**Issue by diaz13** [kwongj/maskrc-svg#6]
Hi
i run this command : ./maskrc-svg.py --aln genome1.aln --out outfile clonalframeresult1 --svgcolour COLOUR --regions FILE --svg FILE

And i obtain this error:
writing masked alignment to outfile ...
Drawing SVG to FILE ...
Traceback (most recent call last):
File "./maskrc-svg.py", line 222, in
rect(x,p,w,colour) # regions
File "./maskrc-svg.py", line 183, in rect
dwg.add(dwg.rect(insert=((xs)+5, (ph)+5), size=(w, h*0.8), fill=colour))
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/elementfactory.py", line 68, in call
return self.cls(*args, **kwargs)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/shapes.py", line 64, in init
super(Rect, self).init(**extra)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/base.py", line 69, in init
self.update(extra)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/base.py", line 85, in update
self.setitem(key, value)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/base.py", line 162, in setitem
self.validator.check_svg_attribute_value(self.elementname, key, value)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/validator2.py", line 62, in check_svg_attribute_value
self._check_svg_value(elementname, attributename, value)
File "/home/user/anaconda3/lib/python3.6/site-packages/svgwrite/validator2.py", line 79, in _check_svg_value
raise TypeError("'%s' is not a valid value for attribute '%s' at svg-element <%s>." % (value, attributename, elementname))
TypeError: 'COLOUR' is not a valid value for attribute 'fill' at svg-element .

i don't no why ??

**Comment by Diamonds95** [comment]
I think you can replace the 'COLOUR' by a specific word, like red,  blue, yellow.
